spring.application.name=Diplom
spring.datasource.url= jdbc:postgresql://localhost:5432/Diplom
spring.datasource.username= Practicant
spring.datasource.password= 123456789
image.upload.dir=/path/to/your/upload/directory
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
# Hibernate ddl auto (create, create-drop, validate, update)
spring.jpa.hibernate.ddl-auto= update
server.port=8080
# logging.level.org.springframework.security=DEBUG
# image.upload.directory = avatar