

spring.datasource.url=jdbc:postgresql://localhost:5432/ads
spring.datasource.username=ads
spring.datasource.password=ads
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQL10Dialect


spring.jpa.show-sql=true