CREATE TABLE avito.ads (
                           id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           title VARCHAR(255) NOT NULL,
                           price INTEGER NOT NULL,
                           description TEXT NOT NULL,
                           image VARCHAR(255),
                           author_id INTEGER NOT NULL,
                           CONSTRAINT fk_ads_author FOREIGN KEY (author_id) REFERENCES avito.users(id) ON DELETE CASCADE
);