CREATE TABLE avito.comments (
                                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                text TEXT NOT NULL,
                                created_at TIMESTAMP NOT NULL,
                                author_id INTEGER NOT NULL,
                                ad_id INTEGER NOT NULL,
                                CONSTRAINT fk_comments_author FOREIGN KEY (author_id) REFERENCES avito.users(id) ON DELETE CASCADE,
                                CONSTRAINT fk_comments_ad FOREIGN KEY (ad_id) REFERENCES avito.ads(id) ON DELETE CASCADE
);