CREATE TABLE comments (
                          id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          text TEXT NOT NULL,
                          created_at TIMESTAMP NOT NULL,
                          author_id INT NOT NULL,
                          ad_id INT NOT NULL,
                          CONSTRAINT fk_comments_author FOREIGN KEY (author_id) REFERENCES users(id),
                          CONSTRAINT fk_comments_ad FOREIGN KEY (ad_id) REFERENCES ads(id)
);