spring.application.name=avito

server.port=8081

spring.servlet.multipart.max-file-size=30MB
spring.servlet.multipart.max-request-size=30MB

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.schemas=avito
spring.flyway.default-schema=avito
spring.flyway.create-schemas=true

spring.jpa.properties.hibernate.default_schema=avito

app.images.dir=${APP_IMAGES_DIR:/images}