spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://avito-db:5432/avito_db?currentSchema=avito}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:avito_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:avito_password}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.flyway.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://avito-db:5432/avito_db?currentSchema=avito}
spring.flyway.user=${SPRING_DATASOURCE_USERNAME:avito_user}
spring.flyway.password=${SPRING_DATASOURCE_PASSWORD:avito_password}