spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.schemas=avito
spring.flyway.default-schema=avito
spring.flyway.create-schemas=true

spring.jpa.properties.hibernate.default_schema=avito

app.images.dir=build/test-images