CREATE TABLE ads (
                     id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                     title VARCHAR(255) NOT NULL,
                     price INT NOT NULL,
                     description TEXT NOT NULL,
                     image VARCHAR(255),
                     author_id INT NOT NULL,
                     CONSTRAINT fk_ads_author FOREIGN KEY (author_id) REFERENCES users(id)
);